/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-07-28 05:35:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Pay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/WWW/20062481_NguyenDangTruong_DeTai26/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/WebBanDungCuTheThao/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fmt.tld", Long.valueOf(1602848772000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1722109420514L));
    _jspx_dependants.put("jar:file:/D:/WWW/20062481_NguyenDangTruong_DeTai26/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/WebBanDungCuTheThao/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/fn.tld", Long.valueOf(1602848772000L));
    _jspx_dependants.put("jar:file:/D:/WWW/20062481_NguyenDangTruong_DeTai26/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/WebBanDungCuTheThao/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Thanh Toán</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\"\r\n");
      out.write("	integrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	background: linear-gradient(10deg, #344c4c, #001a33);\r\n");
      out.write("	border-radius: 1px;\r\n");
      out.write("	box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo-left {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo-right {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo img {\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	width: 50px;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo h1 {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	text-shadow: 1px 1px 0 #000, 2px 2px 0 #000, 3px 3px 0 #000, 4px 4px 0\r\n");
      out.write("		#000, 5px 5px 0 #000;\r\n");
      out.write("	color: #cccccc;\r\n");
      out.write("	font-weight: 100;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-info {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-info h2 {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	color: #8c8c8c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons img {\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	width: 40px;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("	background-color: #cc9900;\r\n");
      out.write("	height: 130px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header nav {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header nav ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header nav ul li {\r\n");
      out.write("	display: inline;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("	transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header nav ul li a {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header nav ul li a:hover {\r\n");
      out.write("	background-color: #995c00;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header nav ul li form {\r\n");
      out.write("	display: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header nav ul li form input {\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header nav ul li form button {\r\n");
      out.write("	padding: 5px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header nav ul li form a img {\r\n");
      out.write("	padding: 5px 10px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	width: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".memu-icons {\r\n");
      out.write("	height: 15px;\r\n");
      out.write("	width: 15px;\r\n");
      out.write("	margin: 0 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ul {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	height: 0px;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ul-right {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-menu {\r\n");
      out.write("	display: none;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	right: 15px;\r\n");
      out.write("	top: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-menu a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	margin: 5px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-icon {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("main {\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	flex: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("	background-color: #333;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 10px 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer div h4 {\r\n");
      out.write("	color: #cc9900;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer h1 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer form {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer div p {\r\n");
      out.write("	color: #cccccc;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	line-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer form {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer form input[type=\"text\"] {\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer form button {\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	background-color: #cc9900;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-img-top {\r\n");
      out.write("	height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-text {\r\n");
      out.write("	text-decoration: line-through;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	padding-top: 5px;\r\n");
      out.write("	margin: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-text-giam {\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	color: #cc2900;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-item {\r\n");
      out.write("	width: 400px;\r\n");
      out.write("	height: 600px;\r\n");
      out.write("	margin: 20px;\r\n");
      out.write("	transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-item:hover {\r\n");
      out.write("	transform: translateY(-5px);\r\n");
      out.write("	box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-md-4 {\r\n");
      out.write("	transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-md-4:hover {\r\n");
      out.write("	transform: translateY(-5px);\r\n");
      out.write("	box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".conter {\r\n");
      out.write("	margin-left: 40px;\r\n");
      out.write("	margin-left: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custom-row {\r\n");
      out.write("	padding-left: 50px;\r\n");
      out.write("	max-width: 1900px;\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write(".form-group{\r\n");
      out.write("font-size: 19px;\r\n");
      out.write("text-align: left;\r\n");
      out.write("width: 500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	function toggleUserMenu() {\r\n");
      out.write("		var userMenu = document.getElementById(\"user-menu\");\r\n");
      out.write("		if (userMenu.style.display === \"block\") {\r\n");
      out.write("			userMenu.style.display = \"none\";\r\n");
      out.write("		} else {\r\n");
      out.write("			userMenu.style.display = \"block\";\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(\r\n");
      out.write("			function() {\r\n");
      out.write("				$('#filterByCategory').change(\r\n");
      out.write("						function() {\r\n");
      out.write("							var selectedCategoryId = $(this).val();\r\n");
      out.write("							$('.product-item').hide(); // Ẩn tất cả các sản phẩm\r\n");
      out.write("\r\n");
      out.write("							if (selectedCategoryId === '') {\r\n");
      out.write("								$('.product-item').show(); // Hiển thị lại nếu chọn \"Chọn loại sản phẩm\"\r\n");
      out.write("							} else {\r\n");
      out.write("								$(\r\n");
      out.write("										'.product-item[data-category=\"'\r\n");
      out.write("												+ selectedCategoryId + '\"]')\r\n");
      out.write("										.show(); // Hiển thị sản phẩm thuộc loại được chọn\r\n");
      out.write("							}\r\n");
      out.write("						});\r\n");
      out.write("			});\r\n");
      out.write("	function handleProductListClick() {\r\n");
      out.write("		// Làm bất cứ điều gì bạn cần ở đây, ví dụ như kích hoạt chức năng lọc sản phẩm\r\n");
      out.write("		var select = document.getElementById('filterByCategory');\r\n");
      out.write("		if (select) {\r\n");
      out.write("			// Trigger event lọc sản phẩm\r\n");
      out.write("			var event = new Event('change');\r\n");
      out.write("			select.dispatchEvent(event);\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"logo\">\r\n");
      out.write("			<div class=\"logo-left\">\r\n");
      out.write("				<img alt=\"\" src=\"IMG/logo.png\">\r\n");
      out.write("				<h1>SPORTS EQUIPMENT MIX</h1>\r\n");
      out.write("				<div class=\"contact-info\">\r\n");
      out.write("					<img alt=\"\" src=\"IMG/thu.png\" class=\"social-icons\">\r\n");
      out.write("					<h2>nguyendangtruong22042002@gmail.com</h2>\r\n");
      out.write("					<img alt=\"\" src=\"IMG/call.png\" class=\"social-icons\">\r\n");
      out.write("					<h2>0326923816</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"logo-right\">\r\n");
      out.write("				<img alt=\"\" src=\"IMG/faceboock.png\" class=\"social-icons\"> <img\r\n");
      out.write("					alt=\"\" src=\"IMG/inta.png\" class=\"social-icons\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"menu\">\r\n");
      out.write("			<nav>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<div class=\"ul\">\r\n");
      out.write("						<div class=\"ul-left\">\r\n");
      out.write("							<li><a href=\"index.jsp\"><img alt=\"\" src=\"IMG/home.png\"\r\n");
      out.write("									class=\"memu-icons\">TRANG CHỦ</a></li>\r\n");
      out.write("							<li><a href=\"ProductsServlet\"><img alt=\"\"\r\n");
      out.write("									src=\"IMG/menu.png\" class=\"memu-icons\">DANH SÁCH SẢN PHẨM</a></li>\r\n");
      out.write("							<li><a href=\"products.jsp\"><img alt=\"\"\r\n");
      out.write("									src=\"IMG/tintuc.png\" class=\"memu-icons\">TIN TỨC</a></li>\r\n");
      out.write("							<li><a href=\"products.jsp\"><img alt=\"\"\r\n");
      out.write("									src=\"IMG/user.png\" class=\"memu-icons\">GIỚI THIỆU</a></li>\r\n");
      out.write("							<li><a href=\"products.jsp\"><img alt=\"\"\r\n");
      out.write("									src=\"IMG/sale.png\" class=\"memu-icons\">CHÍNH SÁCH</a></li>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"ul-right\">\r\n");
      out.write("							<li>\r\n");
      out.write("								<form action=\"search.jsp\" method=\"get\">\r\n");
      out.write("									<input type=\"text\" name=\"query\" placeholder=\"Tìm kiếm...\">\r\n");
      out.write("									<button type=\"submit\">SEARCH</button>\r\n");
      out.write("								</form>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li><a href=\"#\" class=\"user-icon\" onclick=\"toggleUserMenu()\"><img\r\n");
      out.write("									alt=\"\" src=\"IMG/user.png\" style=\"height: 40px; width: 40px\"></a>\r\n");
      out.write("								<div id=\"user-menu\" class=\"user-menu\">\r\n");
      out.write("									");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								</div></li>\r\n");
      out.write("							<li><div style=\"display: flex;\">\r\n");
      out.write("							<a href=\"Cart.jsp\"><img alt=\"\" src=\"IMG/cart.png\"\r\n");
      out.write("									style=\"height: 40px; width: 40px;\"> </a>\r\n");
      out.write("									<div style=\"border-radius: 15px; border: 2px solid #ffffff; position: absolute; margin-left: 30px; \r\n");
      out.write("									background-color: red; width: 25px; height: auto ; max-width:auto; text-align: center; color: white; font-size: 15px\r\n");
      out.write("									\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(cart.carts)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("</div>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<main style=\"width: auto; height: auto;\">\r\n");
      out.write("\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"display: flex; width: 1750px; height: auto	; margin: 20px; margin-left: 130px; justify-content: space-between\">\r\n");
      out.write("			<div\r\n");
      out.write("				style=\"border-radius: 5px; border: 2px solid #6c757d; width: 1300px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2)\">\r\n");
      out.write("				\r\n");
      out.write("				<div style=\"width: 1250px; margin-left: 20px\">\r\n");
      out.write("				<h2\r\n");
      out.write("					style=\"font-size: 33px; text-align: left; width: 200px; margin-top: 20px; color: #000099; font-weight: bold;\">Thanh Toán</h2>\r\n");
      out.write("					<hr style=\"background-color: #cc6600; height: 1.5px\">\r\n");
      out.write("            <div class=\"\">\r\n");
      out.write("            		\r\n");
      out.write("                    <div style=\"display: flex;\">\r\n");
      out.write("                    	<div style=\"display: flex;flex-direction: column;\">\r\n");
      out.write("                    	<h4 style=\"text-align: left; width: 300px;color: #000099;\">Thông tin thanh toán</h4>\r\n");
      out.write("          ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                <form action=\"PayServlet\" method=\"post\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputName\">Họ và tên</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"inputName\" name=\"fullName\" placeholder=\"Họ tên đầy đủ\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("	                    <div class=\"form-group\">\r\n");
      out.write("	                        <label for=\"inputEmail\">Email</label>\r\n");
      out.write("	                        <input  type=\"email\" class=\"form-control\" id=\"inputEmail\" name=\"email\" placeholder=\"...@gmail.com\" required>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    \r\n");
      out.write("	                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"paymentMethod\">Hình thức thanh toán</label>\r\n");
      out.write("                        <select class=\"form-control\" id=\"paymentMethod\" name=\"paymentMethod\" style=\"width: 400px;\" required>\r\n");
      out.write("                            <option value=\"Nhận hàng trước khi thanh toán\">Nhận hàng trước khi thanh toán</option>\r\n");
      out.write("                            <option value=\"Thanh toán chuyển khoản trước\">Thanh toán chuyển khoản trước</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("	                    	</div>\r\n");
      out.write("	                    \r\n");
      out.write("                    	\r\n");
      out.write("                    	<div style=\"margin-left: 100px\">\r\n");
      out.write("                    	<h4 style=\"text-align: left; width: 300px;color: #000099;\">Thông tin giao hàng</h4>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputAddress\">Địa chỉ giao hàng</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"inputAddress\" name=\"address\" placeholder=\"Ghi ghi số nhà..\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputPhone\">Số điện thoại </label>\r\n");
      out.write("                        <input type=\"tel\" class=\"form-control\" id=\"inputPhone\" name=\"phone\" placeholder=\"Liên hệ khi gọi giao hàng...\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                     <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"ghichu\">Ghi chú</label>  \r\n");
      out.write("                        <textarea style=\"width: 500px\" class=\"form-control\" rows=\"\" cols=\"\" id=\"ghichu\" name=\"ghichu\"  placeholder=\"Ghi chú ý về đơn hàng , ví dụ thời gian lấy hàng hay chỉ dẫn địa điểm giao hàng chi tiết hơn...\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    	</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <h4 style=\"text-align: left; width: 300px;color: #000099;\">Thông tin mua hàng</h4>\r\n");
      out.write("                    <table class=\"table table-bordered\">\r\n");
      out.write("                        <thead class=\"thead-light\">\r\n");
      out.write("                            <tr style=\"font-size: 20px ; text-align: center;\">\r\n");
      out.write("                                \r\n");
      out.write("                                <th>Sản phẩm</th>\r\n");
      out.write("                                <th>Giá</th>\r\n");
      out.write("                                <th>Tạm tính</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("								<td colspan=\"1\"><h5 style=\"color: black; font-weight: bold;\">Tạm tính</h5></td>\r\n");
      out.write("								<td colspan=\"2\"><h5 style=\"color: black; font-weight: bold;\">");
      if (_jspx_meth_fmt_005fformatNumber_005f2(_jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("						\r\n");
      out.write("							</tr>\r\n");
      out.write("							  <tr>\r\n");
      out.write("								<td colspan=\"1\"><h5 style=\"color: black; font-weight: bold;\">Giao hàng</h5></td>\r\n");
      out.write("								<td colspan=\"2\"><h5 style=\"color: black; font-weight: bold;\">Giao hàng miễn phí.</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							 <tr>\r\n");
      out.write("								<td colspan=\"1\"><h4 style=\"color: black; font-weight: bold;\">Tổng tiền</h4></td>\r\n");
      out.write("								<td colspan=\"2\"><h4 style=\"color: black; font-weight: bold;\">");
      if (_jspx_meth_fmt_005fformatNumber_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								<input type=\"hidden\" id=\"totalAmount\" name=\"totalAmount\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.orderTotal}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("$\" readonly></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"processPayment\">\r\n");
      out.write("                    <input type=\"submit\" class=\"btn btn-primary\" value=\"Xác Nhận Thanh Toán\" style=\" width: 400px; height: 50px; \r\n");
      out.write("						font-size: 20px; font-weight: bold; background-color:  #995c00; color: white; border: none;border-radius: 3px \">\r\n");
      out.write("                    <div style=\"height: 50px\"></div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			<div\r\n");
      out.write("				style=\"display: flex; flex-direction: column; width: 400px; height: auto; \">\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"width: 400px; height: 300px;  border-radius: 5px; border: 2px solid #6c757d;\">\r\n");
      out.write("					<h2\r\n");
      out.write("						style=\"font-size: 33px; color: white; color: white; background-color: #cc9900; width: 400px; height: 50px; font-weight: bold; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2)\">\r\n");
      out.write("						<i class=\"fas fa-people-carry\" style=\"color: blue; margin: 10px\"></i>HỔ\r\n");
      out.write("						TRỢ ONLINE\r\n");
      out.write("					</h2>\r\n");
      out.write("\r\n");
      out.write("					<div\r\n");
      out.write("						style=\"display: flex; width: 400px; align-items: center; height: 50px\">\r\n");
      out.write("						<p\r\n");
      out.write("							style=\"font-size: 18px; font-weight: bold; color: #0052cc; margin-left: 20px; margin-top: 10px\">TƯ\r\n");
      out.write("							VẤN BÁN HÀNG</p>\r\n");
      out.write("						<p\r\n");
      out.write("							style=\"font-size: 27px; font-weight: bold; color: #339933; margin-left: 20px\">0123456789</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div\r\n");
      out.write("						style=\"display: flex; width: 400px; align-items: center; height: 30px\">\r\n");
      out.write("						<img alt=\"\" src=\"IMG/zalo.png\"\r\n");
      out.write("							style=\"width: 40px; height: 40px; margin-left: 20px;\">\r\n");
      out.write("						<p\r\n");
      out.write("							style=\"font-size: 20px; font-weight: bold; color: red; margin-left: 10px; margin-top: 20px\">0123456789</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div\r\n");
      out.write("						style=\"display: flex; width: 400px; align-items: center; height: 100px\">\r\n");
      out.write("						<p\r\n");
      out.write("							style=\"font-size: 18px; font-weight: bold; color: #0052cc; margin-left: 20px; margin-top: 10px\">HỔ\r\n");
      out.write("							TRỢ KỸ THUẬT</p>\r\n");
      out.write("						<p\r\n");
      out.write("							style=\"font-size: 27px; font-weight: bold; color: #339933; margin-left: 20px\">0326923816</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div\r\n");
      out.write("						style=\"display: flex; width: 400px; align-items: center; height: 30px\">\r\n");
      out.write("						<img alt=\"\" src=\"IMG/zalo.png\"\r\n");
      out.write("							style=\"width: 40px; height: 40px; margin-left: 20px;\">\r\n");
      out.write("						<p\r\n");
      out.write("							style=\"font-size: 20px; font-weight: bold; color: red; margin-left: 10px; margin-top: 20px\">0326923816</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<div>\r\n");
      out.write("		<img alt=\"\" src=\"IMG/cuối.png\" style=\"width: 100%\">\r\n");
      out.write("	</div>\r\n");
      out.write("	<footer>\r\n");
      out.write("		<h1>THÔNG TIN LIÊN LIÊN HỆ CỦA CHÚNG TÔI</h1>\r\n");
      out.write("		<form action=\"search.jsp\" method=\"get\">\r\n");
      out.write("			<input type=\"text\" name=\"query\"\r\n");
      out.write("				placeholder=\"Nhập Email nhận tin khuyến mãi\">\r\n");
      out.write("			<button type=\"submit\">ĐĂNG KÝ</button>\r\n");
      out.write("		</form>\r\n");
      out.write("		<div style=\"display: flex; justify-content: space-around;\">\r\n");
      out.write("			<div style=\"align-items: center;\">\r\n");
      out.write("				<h4>SPORTS EQUIPMENT MIX</h4>\r\n");
      out.write("				<p>\r\n");
      out.write("					SPORTS EQUIPMENT MIX nhà cung cấp<br> dụng cụ thể thao hàng\r\n");
      out.write("					đầu tại Việt Nam.<br> Với SPORTS EQUIPMENT MIX chất lượng sản\r\n");
      out.write("					<br> phẩm được ưu tien hàng đầu, uy tín là tiêu<br> chí\r\n");
      out.write("					phát triển của chúng tôi.Hy vọng sảm <br> phẩm làm cho bạn hài\r\n");
      out.write("					lòng khi sử dụng.\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<h4>Sinh viên thực hiện</h4>\r\n");
      out.write("				<p>Nguyễn Đang Trường</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<h4>MSSV</h4>\r\n");
      out.write("				<p>20062481</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<h4>THÔNG TIN LIÊN HỆ</h4>\r\n");
      out.write("				<p>\r\n");
      out.write("					Hiện shop chỉ bán online, không tiếp <br> khách đến cửa hàng.\r\n");
      out.write("				</p>\r\n");
      out.write("				<p>\r\n");
      out.write("					Thời gian làm việc: 8g00 đến 17g00,từ <br> thứ 2 đến thứ 7\r\n");
      out.write("					(nghỉ trưa từ 12g đến 13g). Những giờ khác tư vấn online.<br>\r\n");
      out.write("					SĐT liên hệ ngoài giờ :0326923816\r\n");
      out.write("				</p>\r\n");
      out.write("				<p>Email:nguyendangtruong22042002@hmail.com</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Modal/register.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Modal/verify.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Modal/login.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	 <script>\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("            // Kiểm tra nếu thuộc tính \"showVerifyModal\" có trong session và có giá trị true\r\n");
      out.write("            ");
 if (session.getAttribute("showVerifyModal") != null && (Boolean) session.getAttribute("showVerifyModal")) { 
      out.write("\r\n");
      out.write("                $('#verifyModal').modal('show');\r\n");
      out.write("                ");
 session.removeAttribute("showVerifyModal"); 
      out.write("\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        // Kiểm tra nếu thuộc tính \"registerSuccess\" có trong session và có giá trị true\r\n");
      out.write("        ");
 if (session.getAttribute("registerSuccess") != null) { 
      out.write("\r\n");
      out.write("            ");
 Boolean registerSuccess = (Boolean) session.getAttribute("registerSuccess"); 
      out.write("\r\n");
      out.write("            ");
 if (registerSuccess) { 
      out.write("\r\n");
      out.write("                $('#registerSuccessModal').modal('show');\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                $('#registerFailureModal').modal('show');\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 session.removeAttribute("registerSuccess"); 
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("	<!-- Modal Đăng Ký Thành Công -->\r\n");
      out.write("<div class=\"modal fade\" id=\"registerSuccessModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"registerSuccessModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"registerSuccessModalLabel\">Đăng ký thành công</h5>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("           Chúc mừng!. Xác thực tài khoản thành công\r\n");
      out.write("             .  Bạn đã đăng ký thành công. Vui lòng đăng nhập lại.\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Đóng</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal Đăng Ký Không Thành Công -->\r\n");
      out.write("<div class=\"modal fade\" id=\"registerFailureModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"registerFailureModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"registerFailureModalLabel\">Đăng ký không thành công</h5>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                Đăng ký không thành công. Mã xác thực bạn nhập không chính xác. Vui lòng thử lại.\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Đóng</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("	<!-- JavaScript để hiển thị modal khi cần -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal Đăng nhập thành công -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"loginSuccessModal\" tabindex=\"-1\"\r\n");
      out.write("		role=\"dialog\" aria-labelledby=\"loginSuccessModalLabel\"\r\n");
      out.write("		aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"loginSuccessModalLabel\">Đăng Nhập\r\n");
      out.write("						Thành Công</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">Chào mừng bạn đã đăng nhập thành công.\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Đóng</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        \r\n");
      out.write("        ");
 if (session.getAttribute("loginSuccess") != null && (Boolean) session.getAttribute("loginSuccess")) { 
      out.write("\r\n");
      out.write("            $('#loginSuccessModal').modal('show');\r\n");
      out.write("            ");
 session.removeAttribute("loginSuccess"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            // Thay đổi nút \"Đăng Nhập\" và \"Đăng Ký\" thành nút \"Đăng Xuất\"\r\n");
      out.write("            var tenuser = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.ten}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'; // Lấy tên người dùng từ session\r\n");
      out.write("            $('#user-menu').html('<span class=\"user-info font-weight-bold text-black\">Xin Chào  ' + tenuser + '</span>' +\r\n");
      out.write("                '<button type=\"button\" class=\"btn btn-danger\" onclick=\"confirmLogout()\">Đăng Xuất</button>');\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function confirmLogout() {\r\n");
      out.write("        // Hiển thị modal xác nhận đăng xuất\r\n");
      out.write("        $('#confirmLogoutModal').modal('show');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function logout() {\r\n");
      out.write("    	window.location.href = \"LogoutServlet\";\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("	<!-- Modal Đăng nhập không thành công -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"loginFailedModal\" tabindex=\"-1\"\r\n");
      out.write("		role=\"dialog\" aria-labelledby=\"loginFailedModalLabel\"\r\n");
      out.write("		aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"loginFailedModalLabel\">Đăng Nhập\r\n");
      out.write("						Không Thành Công</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">Đăng nhập không thành công. Vui lòng\r\n");
      out.write("					kiểm tra lại email và mật khẩu.</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Đóng</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
 if (session.getAttribute("loginFailed") != null && (Boolean) session.getAttribute("loginFailed")) { 
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            $('#loginFailedModal').modal('show');\r\n");
      out.write("        ");
 }
           session.removeAttribute("loginFailed");
        
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("	<!-- Modal xác nhận đăng xuất -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"confirmLogoutModal\" tabindex=\"-1\"\r\n");
      out.write("		role=\"dialog\" aria-labelledby=\"confirmLogoutModalLabel\"\r\n");
      out.write("		aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"confirmLogoutModalLabel\">Xác nhận\r\n");
      out.write("						đăng xuất</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">Bạn có chắc chắn muốn đăng xuất không?\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Hủy</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-primary\" onclick=\"logout()\">Đăng\r\n");
      out.write("						xuất</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("										");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("										");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /Pay.jsp(379,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.ten}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("											<span class=\"user-info font-weight-bold text-black\"> ");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("											</span>\r\n");
          out.write("											<button type=\"button\" class=\"btn btn-danger\"\r\n");
          out.write("												onclick=\"confirmLogout()\">Đăng Xuất</button>\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /Pay.jsp(380,64) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("Xin chào: ${sessionScope.ten}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("											<button type=\"button\" class=\"btn btn-primary\"\r\n");
          out.write("												data-toggle=\"modal\" data-target=\"#loginModal\">Đăng\r\n");
          out.write("												Nhập</button>\r\n");
          out.write("											<button type=\"button\" class=\"btn btn-primary\"\r\n");
          out.write("												data-toggle=\"modal\" data-target=\"#registerModal\">Đăng\r\n");
          out.write("												Ký</button>\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /Pay.jsp(428,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty cart.carts}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Pay.jsp(429,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cartItems");
      // /Pay.jsp(429,12) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/Pay.jsp(429,12) '${cart.carts}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cart.carts}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Pay.jsp(429,12) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("session");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /Pay.jsp(430,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("totalAmount");
      // /Pay.jsp(430,12) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/Pay.jsp(430,12) '${cart.orderTotal}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cart.orderTotal}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Pay.jsp(430,12) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setScope("session");
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /Pay.jsp(480,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /Pay.jsp(480,28) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/Pay.jsp(480,28) '${cart.carts}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cart.carts}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Pay.jsp(480,28) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("counter");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                <tr style=\"font-size: 20px; color: #666666; text-align: center;\">\r\n");
            out.write("                                    \r\n");
            out.write("                                  	<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.tensanpham}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" <i style=\"color: red\" class=\"fas fa-times\">  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.soluongmua}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</i></td>\r\n");
            out.write("                                    \r\n");
            out.write("                                    <td>");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" </td>\r\n");
            out.write("                                    <td>");
            if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" </td>\r\n");
            out.write("                                </tr>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /Pay.jsp(485,40) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.giagiam}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /Pay.jsp(485,40) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setType("currency");
      // /Pay.jsp(485,40) name = currencySymbol type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setCurrencySymbol("₫");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /Pay.jsp(486,40) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.tamtinh}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /Pay.jsp(486,40) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setType("currency");
      // /Pay.jsp(486,40) name = currencySymbol type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setCurrencySymbol("₫");
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f2_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f2.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f2.setParent(null);
      // /Pay.jsp(491,69) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.orderTotal}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /Pay.jsp(491,69) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setType("currency");
      // /Pay.jsp(491,69) name = currencySymbol type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f2.setCurrencySymbol("₫");
      int _jspx_eval_fmt_005fformatNumber_005f2 = _jspx_th_fmt_005fformatNumber_005f2.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f2);
      _jspx_th_fmt_005fformatNumber_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f2, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f3_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f3.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f3.setParent(null);
      // /Pay.jsp(500,69) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart.orderTotal}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      // /Pay.jsp(500,69) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f3.setType("currency");
      // /Pay.jsp(500,69) name = currencySymbol type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f3.setCurrencySymbol("₫");
      int _jspx_eval_fmt_005fformatNumber_005f3 = _jspx_th_fmt_005fformatNumber_005f3.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005ftype_005fcurrencySymbol_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f3);
      _jspx_th_fmt_005fformatNumber_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f3, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f3_reused);
    }
    return false;
  }
}
